### PR TITLE
Updated brazilian portuguese translation

### PR DESCRIPTION
**Pull request by Felipefpl**
Their descriptions are already displayed in the submissions.

### CODE REVIEW

**Review by zelurker — CHANGES_REQUESTED** [review]
Changes to raine.pot are useless : this file is generated from the source files, that's the source files that you need to change for that, not raine.pot itself, so you can remove this part from your PR... ! (funny that mer-curious missed that !).

**Comment by Felipefpl** [comment]
Is it good now?

**Comment by zelurker** [comment]
it would have been better to just delete your commit for raine.pot from your PR, I merged the PR anyway but it deleted the raine.pot file. Not a problem for me, I can leave it outside of git, but it will be a problem for you if you can't generate it... So if you need it, tell me !

**Comment by Felipefpl** [comment]
Strange, since i deleted the raine.pot file.

**Comment by zelurker** [comment]
Yeah what I said the file is no longer in git, I don't have a problem with that, but you might if you can't recreate it.

**Comment by Felipefpl** [comment]
Nah, dont worry about that. Just deleted the file so you could submit my pull request. ;)

**Pull request merged**
