### PR TITLE
Added translation

### PR DESCRIPTION
**Pull request by Felipefpl**
Added a brazilian portuguese translation, also, i wasnt able to add manually this translation to raine even creating/naming the folders like the other ones, i had to replace the .mo file of the spanish translation to check my work.

### CODE REVIEW

**Comment by zelurker** [comment]
Ok I just committed this, I just changed the lines including % signs which were not compiled by msgfmt (I hadn't even noticed the problem with the other locales), you just need to put a double % in this case : %%.
And I renamed your po file to pt_br.po, shorter without spaces, easier to manipulate.
The big problem is that I never had such a locale till now in raine. So far the locale are on 2 chars only for the main country. Well for simplicity I'll try to keep the 2 chars locale for now, but I might have to change that if some day someone comes with a pure Portuguese locale !
You can see the changes in git, I tested it by setting my locale to pt_BR.UTF-8, it works.
And it should also detect a pt_BR locale in windows. And you can also force the setting tn the options dialog...
Everything should be fine !

**Comment by Felipefpl** [comment]
I see, thanks for the explanation.

**Comment by zelurker** [comment]
After some thought, for the bld files, I don't know how but the problem was that you had a comment inserted before the lines, saying:
#, c-format
that's was because of it that the string was interpreted as a sprintf format string with its %.
So just remove the comment, and forget the double %, it's not a sprintf string we can't have a double % here.
Comment done.
And I don't know how, I used git mv to rename your file to pt_br.po, but somehow this got split in more than 1 commit, the deletion for the old file has only been applied now... oh well...

**Comment by Felipefpl** [comment]
I didnt insert any comment, i use poedit, it doesnt allow the user to mess with the code mostly, only the translation.

**Comment by zelurker** [comment]
Yeah I was almost sure this had been added by some software... Well it
could have been right !
Anyway it doesn't matter, problem fixed ! (I posted on the forum about your
translation, and I found out this morning internet archive had a full
archive for raine 0.91.4 roms so raine uses that to download its roms from
now on).

**Comment by Felipefpl** [comment]
> Yeah I was almost sure this had been added by some software... Well it could have been right ! Anyway it doesn't matter, problem fixed ! (I posted on the forum about your translation, and I found out this morning internet archive had a full archive for raine 0.91.4 roms so raine uses that to download its roms from now on).

good to know it's fixed, thanks for that. :)

it's GREAT you can post about roms in your site btw. :D

**Comment by zelurker** [comment]
Well since they are hosted on internet archive, it's considered common good
and no more piracy. It makes things much easier for sure.

**Comment by Felipefpl** [comment]
> Well since they are hosted on internet archive, it's considered common good and no more piracy. It makes things much easier for sure.

Really? I didnt know that, good indeed. :)

**Pull request merged**
