### PR TITLE
New default speed for NGCD loading animations + some minor text revisions

### PR DESCRIPTION
**Pull request by dezraj**
The default NGCD loading speed time is now 2x to match the one used in the latest NGCD hardware model, the NGCDZ. There is a thread in the Neo-Geo.com forums with a thorough inspection on this matter, here:
https://www.neo-geo.com/forums/index.php?threads/neo-geo-cdz-single-or-double-speed-lets-discuss.256310/

I also found a YouTube video which compares the loading speed between the NGCD and NGCDZ consoles, here:
https://www.youtube.com/watch?v=0rrNRrEhyUM

According to my observation, the first KOF'98 loading animation (the one with the spinning SNK logo) takes the following time until the game menu is finally shown on screen:

NGCD: 28 seconds
NGCDZ: 16 seconds

In Raine, I observed the following times for the same scenario:

1x speed: 18 seconds
2x speed: 10 seconds

So apparently the real hardware loads the files a little slower than Raine in both CD-ROM speed settings, and the NGCDZ's 2x speed CD-ROM drive is more similar to Raine's 1x setting. I have found a source which may possibly explain why the real hardware loading speed is slower, here:
https://wiki.neogeodev.org/index.php?title=Loading_time

Anyway, since 1x is too slow for today's emulation standards, I suppose 2x may work as a balance between the real hardware experience and the emulation improvements to primarily suggest it to new users. According to my testings, any speed setting above that may feel a little too fast for some loading animations, and SNK introduced artistical animations in late NGCD ports, such as Samurai Spirits 3, KOF'96 and The Last Blade 2.

### CODE REVIEW

**Comment by zelurker** [comment]
Sorry but I am absolutely not interested by that. The speed difference is because of the seek time obviously, a real cdrom drive has quite a heavy head for reading which takes quite some time to move from 1 track to another track on the cd, raine just takes into account the file transfer rate : cdrom 1x is 150Kb/s, so that's what is measured here, and seek time is just 0 !
To decide about the default I simply played a few animations, and 8x seems the best choice between too long loading times and it's so fast that you have no time to see anything. I didn't change my opinion on that. Users are free to lower the setting if they want, but I won't change the default.
Mame has added neocd emulation and I am sure that if they don't reach exactly the speed you measured they will be delighted to change their source to try to be as close as possible to the original hardware. That's not my goal here, the goal is just to have fun, and to have something as easy to use as possible, that's all.
And about the text modifications : I don't like caps everywhere, forget about your CUE, I won't even talk about this anymore. iso file is as good as disk image, but here it's really about reading an iso file so iso stays. I'll just manually update the sound commands to sound associations that's all. (and I just noticed that it breaks translations pointing to sound commands instead of sound associations. Too bad, but I already accepted a 1st replacement for that, so it's already broken anyway... tsss !)

**Comment by dezraj** [comment]
Hello! Thank you for considering this PR and sorry for not providing a rationale for my changes.

For the new loading speed setting for NGCD, replaying some NGCD games recently I came to think that it is part of the system-wide experience to deal with these loading animation screens, maybe that's why some of them were artistically worked on by SNK in late NG ports to the system. That's why I felt the need to suggest a new first setting for it, so others could also appropriately experience this feature from the start. I suppose if someone does not enjoy the loading times they may rather look for the original ROM cartridge versions of those titles. The 8x setting virtually eliminates some loading animations according to my testings, so I proposed a little adjustment to this feature to offer a better whole NGCD system experience.

As for the CUE x cue, I looked at the code and most of the instances of this word are already capitalized. There may only be a few ones left which I believe are for debugging, so I ignored them. I came across this one while checking other texts in the code and decided to suggest the capitalization for it for consistency.

I suggested replacing "ISO" for "disc image" because I got this error message while trying to load a BIN file, not an ISO one. Surprisingly Redump.org has changed their ripping standards from ISO to BIN a while ago and original NGCD ISO images are becoming pretty hard to find on the internet. The ones I got from archive.org are all in the new BIN format for both data and audio tracks. You check them here:
https://archive.org/details/rr-snk-neo-geo-cd
So, using "disc image" instead of "ISO" in this GUI message would clearly embrace both new and old copy standards for NGCD game disc images, and Raine does support all of them. That's also the term used by other emulators for disc-based systems such as Duckstation and PCSX2.

Finally, the change from "Sound commands" for "Sound associations" in the menu title was a leftover from the previous change which came unnoticed by me.

Thank you again for your time and consideration.

**Comment by zelurker** [comment]
Very short because I won't talk about that forever :
1) loading speed : default remains at 8x, it's already quite long for some
games at 8x.
2) CUE : my bad, I shouldn't have accepted all these capitalizations !
3) iso : it's still an iso even if it's in a bin file, and even if the
sector size is 2352.

Le jeu. 8 juin 2023 à 09:53, Elvis Araujo ***@***.***> a
écrit :

**Comment by zelurker** [comment]
To be totally honest : disk image is not a bad idea, but it means updating
the translations again and this part is really boring. If you do a PR with
the updated translations included then I'll accept it without problem,
otherwise just forget it, it's easier to keep iso !

Le jeu. 8 juin 2023 à 18:04, Emmanuel Anne ***@***.***> a
écrit :

**Pull request closed without merging**
