### PR TITLE
Remaining editions in the source code files based on the raine.pot file from zelurker/master

### PR DESCRIPTION
**Pull request by dezraj**
These are the remaining editions which I did to the source code files based on the translatable strings in raine.pot file from the main Raine repository (zelurker/master).

I basically did the same as before:

- removed most of the abbreviations and probably a few left spaces between words and colons or words and exclamation points or question marks to match the standard typing for the English language.
- I also reviewed some apologetic expressions in some messages such as "sorry" to possibly match similar messages I saw in other files in the code.
- I am not sure about line 5863 in the raine.pot file, but I suggested the following:
5863 msgid "Test Mode Display"
- updated the Raine web page in opengl.c to raine.1emulation.com which I think is the best place to report issues first in the forum and then file a bug report here in GitHub later if needed.
- I made five individual commits to individual files first and then a combined commit with several changes in different files when I learned how to do this in GitHub Dev interface. But all commits are valid for the changes.

I hope this won't be as difficult as my previous changes to implement now that you have created a script for that. Please let me know if you need any help working on the po files again with these remaining revisions. Thank you so much again.

**PS:** the Japanese strings and weird characters strings weren't changed by me. I guess they are showing as changed strings because the files were converted from a pattern to other (I guess to UTF-8) and then it's causing this error in my commits.

### CODE REVIEW

**Comment by zelurker** [comment]
Yeah these japenese strings are fragile, I'll remove them from the patch.
By the way originally they were some weird encoding in the dos version, never knew which encoding it was, never understood how it worked. I fixed the name in utf8 for some very rare entries, but it's unused anyway, I don't see where and why I would display this anyway. I should probably remove the field one day, it's been there for almost 20 years doing nothing, but today is not the day, I'll just remove all occurences of long_name_jpn from your patch.
Here is a screenshot where your patch tries to destroy one of the strings I restored... !
jap

**Comment by zelurker** [comment]
and abbreviations are sometimes better : when used by print_ingame the message is printed at the bottom of the screen. Depending on the game the place to print the message can be very limited, so I'll keep gfx there instead of graphics.

**Comment by zelurker** [comment]
and the " 2 minutes" to "2  minutes" does probably nothing. The space there was just before probably dates from the dos version where a constant width font was used. Now it's not the case anymore, so the space is probably barely visible now. I accept the patch anyway because it won't do any harm, but it's probably useless.

**Comment by zelurker** [comment]
applied manually, because edited and stripped, the script to update the po files seems to have worked wonderfully, you can check the commits.

**Comment by dezraj** [comment]
Thank you so much for accepting most of my suggestions. Hopefully the translators will find it easier with most of the words no longer abbreviated now.

There is just one minor change which I think was overlooked in your manual editions, which is the double space between the number and the word "Minutes" in the fchamp.c file. It's so subtle that I forgot to implement it in my first commit, so I decided to commit it only in my combined commit later on.

You can check it here:
https://github.com/zelurker/raine/pull/52/commits/a4397e86e126b3906270c36afb0c6c51d9f112c0#diff-ef87801072e7634e199c4a961d379213a548133ec1dbb45353a3fbb76c36a1a4

Not that it makes any difference, but the translations are sometimes following and sometimes correcting this double space. The Spanish corrects it, the others seem to follow the double space as far as I've noticed. Anyway, perhaps it would be better to have the correction in the source raine.pot too to suggest a consistent translation among the different languages.

Thank you so much again.

**PS:** the encoding of the those files with Japanese characters was Shift_JIS according to the GitHub editor. Here's a screenshot of my master branch, which is hopefully out of date so I could get this message again to show you:

image

**Comment by zelurker** [comment]
Yeah it happens when you edit patches manually, it's error prone, no idea
what happened to this "2  minutes" -> "2 minutes", congratulations for
spotting it, even if it's still a detail.
I did the replace manually on fchamp.c, 6 matches actually (just replaced 2
spaces followed by Minutes by 1 space : 6 matches).
I won't commit it now because I'll need to update the translations after
that and I don't want to do that now, I'll see that tomorrow. And it's just
a space issue, something really minor, especially with a variable width
font.
I much prefer when I can apply a patch directly without any editing of
course, but it was clearly impossible with yours. (the update for the pt_br
translation is top for that).
The fact that it destroyed the encoding of the characters shows that it
failed to detect correctly the encoding, you have to be super cautious with
that.
It's easy to see if it's a fixed file, this field will look like garbage if
it's incorrectly detected, but if it's not a fixed one it will always look
bad no matter what, even I probably overwrote some of these with a bad
encoding unwillingly, I try to avoid that as much as possible now.
There are 2 encodings for this particular field depending on which file you
look at, if it's one I fixed, then it's simply utf8. If it's not a fixed
one, it's a "non-iso extended ascii text" is all I could get from my
encoding detector. No idea what this beast is exactly, it might be some
special encoding to display correctly with an old allegro font lost in
time, and not related at all to any special encoding, the dos version was
full of hacks and it would not be so astonishing, not even sure Antiriad
remembers what it is, I never bothered him with that so far.


Le jeu. 29 déc. 2022 à 18:55, Elvis Araujo ***@***.***> a
écrit :

**Comment by zelurker** [comment]
and ps : bublbobl.c for example has a fixed long_name_jpn for this field :
GME( bublbobl, "Bubble Bobble", TAITO, 1986, GAME_PLATFORM,
        .long_name_jpn = "バブルボブル",
        .board = "A78",
but the original encoding is totally different in hex it's 83 6F 83 75 83
8b 83 7b 83 75 83 8b


Le ven. 30 déc. 2022 à 00:32, Emmanuel Anne ***@***.***> a
écrit :

**Comment by zelurker** [comment]
After some more investigation, github is partially right, it's indeed sjis,
but mixed with some old dos file encoding.
Apparently shift-jis or sjis was the way to encode japanese characters, but
it was supposed to be unix only, no crlf at the end of lines like here.
So if you use any modern editor with something like that, it will try to
convert to utf8, there will be trouble, and the field will be destroyed.
It's probably not worth the trouble at all anyway. This field was almost
not used at all, even in the old last dos version, 0.28, it was used only
in -gameinfo to display info about a game, and even then you couldn't see
it because it scrolled past the top of the screen before you had time to
see it! So you needed to redirect the output to a file, and then have
something which knew how to decode sjis to visualize it properly... really
crazy !

So it's just some sjis between the quotes, if you succeed to save this part
alone without conversion, and then use a standard tool to convert sjis to
utf8, you'll correctly see the japenese characters, finally ! But it's a
rather tedious work, and probably useless now.

I'll probably get rid of all this in the coming days then... !

Le ven. 30 déc. 2022 à 00:38, Emmanuel Anne ***@***.***> a
écrit :

**Comment by dezraj** [comment]
Thank you so much for the rich stories on these technical data. It's very interesting to know about those pieces of information even if I don't understand them that much. I only knew Raine in 2009 or 2010 through NeoRaine I guess, so it's interesting to know some of Raine's past.

By the way, I didn't change the other double space entries in the fchamp.c file because those that I edited are the only ones that show in the raine.pot file, so I guess these are the ones that matter most. But it's good anyway that you changed the remaining others, it was certainly a very quick job I suppose. Interestingly the Spanish translator had already ignored the double spaces in the translation but the others decided to keep it as exactly as in the source.

Thank you again for your special time and recent work in the code.

**Comment by zelurker** [comment]
I decided to investigate why this double space, so I reinstalled a very old
dos version to check what the dipswitches look like, and it's an alignment
issue when switching between " 2  Minutes" & "2.5 Minutes", this way the 2
fields have exactly the same width. I don't know why it was so important at
the time, probably only for the look on screen...
[image: raine.png]
[image: raine2.png]

Le ven. 30 déc. 2022 à 04:36, Elvis Araujo ***@***.***> a
écrit :

**Comment by dezraj** [comment]
Thank you so much for the further details. So finally there was a good reason for those useless spaces in the old Raine versions. The pictures aren't showing here I don't know why, but I think I can imagine how it was.

By the way, talking about double spaces, the new additions to the raine.pot have two instances of spaces which I think could be reviewed. Take a look:

The first here:
source/sdl/dialogs/about.cpp:940
#, c-format
msgid "Using "

And the second here:
source/sdl/dialogs/about.cpp:916
#, c-format
msgid "with an unknown gcc ???"

Interestingly the first was kept by the Brazilian translator in his translation, and the second was removed. Apparently he doesn't attentively realize these spaces in every string, perhaps due to the way they show in Po Edit?

Anyway, since we are reviewing these tiny details now, I think in the first case it should be "Using" and in the second, "with an unknown GCC???" with capital letters in the acronym and no space between the word and the question mark to comply with the English standard typing. You can decide if you want to keep three question marks or just one. I think you wanted to emphasize this question here, right?

I'm sorry for being so picky in these little details, but those are the exceptions I found in your recent revision. It was a great work!

Thank you so much again and happy new year! 😊

**Comment by zelurker** [comment]
There is no double space here, it's just using followed by 1 space because
after that arrives the rest of the sentence, see the about dialog to see
how it's used. It's because so far the about dialog was only partially
translated, the "Compiled by " and "Using " remained in english, so I added
these 2 for that.
For the "with an unknown gcc ???", it's in case gcc can't be identified, it
will probably never happen and nobody will ever see this message, it's here
just in case, so no worry, I added a translation for that just in case too,
but it's very unlikely to be visible one day.
Nope for the 1st one, the space is required the rest of the sentence
doesn't start with a space.
Nope for the 2nd, gcc is the name of the command, it's the gnu c compiler,
it takes no cap letter. And for the space before the ???, oh well, I'll
leave this one, it doesn't do much harm as it is now since it will probably
never be visible, and anyway it's a very tiny testimony of my french origin
!
I had lessons on how to type with an old machine writer at school in France
and it leaves traces, I add these spaces without thinking, but it's totally
correct in french.


Le sam. 31 déc. 2022 à 01:45, Elvis Araujo ***@***.***> a
écrit :

**Comment by zelurker** [comment]
For the pictures yeah weird since the other picture showed in the github interface... well you should have received this as an email too, maybe it works better in the mail (these were nice pictures after all !).

**Comment by dezraj** [comment]
Thank you so much for the time commenting my suggestions. Now I see what you meant with the space in the end of "using ". I clicked on "About" in Raine and saw the use case of that. But it's quite unusual to have a space in the end of a sentence or in the beginning of one, which is what was happening with the " 2 minutes" string also. I as a translator would think it was a typo and correct/remove it, which is what the Spanish translator did with the " 2 minutes" in his translation. Interestingly the Brazilian translator kept the space both in the beginning and in the end of those strings, but then he removed the space in "gcc ???", which makes me think he probably does it unintentionally?

To avoid this ambiguous situation in the possibility of translations I think you could perhaps find a way to avoid the word "Using" (without the space) "gluing" with the rest of the words in the menu (the words "SDL-2.0.22, SDL_image-2.0.5..."). But I don't know if that would require a lot of work to do. Does rephrasing it to "Libraries used:" or "Using:" (with the colon) solve the issue and keep the words separated?

As for the space in "gcc ???", I'm ok with your decision, though I think your French origin is within the whole project since you are French and the main maintainer for so long. But anyway, let's see how the translators will see that space...

By the way, I received your GitHub notification in my e-mail but unfortunately the pictures aren't there either. I guess something happened when you tried to upload them to the site? What about uploading those DOS screens to the forum? I believe more users would be interested in seeing how the emulator was 20 years ago.

Thank you so much again for your time and patience and happy 2023!

**Comment by zelurker** [comment]
Don't worry, the brazilian translator accepted that without problem, he
updated his translation and then complained he couldn't see the result, it
was because he needed a new binary, but he doesn't want to try to compile
his own... ! I told him it was easy but for now I sent a new binary, he is
happy everything works.
Doing it this way just avoids to mess with the c-format attribute just
after that, it would look like :
Using SDL-%d.%d.%d, SDL_image-%d.%d.%d, SDL_ttf-%d.%d.%d
knowing that if you translate that you can only change the "Using " part,
and must keep the rest exactly as it is, it's quite frustrating, so it's
simpler to just leave "Use " alone to be translated. That's where it's nice
to see where it comes from in the .po file, you see it's from about.cpp
with the line, so you don't have any trouble to see it's from the about
dialog and understands why it's done this way.

For the attachments, I guess there is a problem when importing a picture in
the body of the mail, it's probably better to leave it as a standard
attachment, but sorry, I already overwrote the 1st picture with a new one,
I have only the 2nd one that I can try to attach to this one.

For GCC you are right, I found some occurrences on the web where they use
GCC all in caps to talk about the project, but as a programmer I use the
gcc command or the gcc package (for installation) too often to write this
in upper case !
Anyway here is the picture again, as a standard attachment this time...

Le dim. 1 janv. 2023 à 01:32, Elvis Araujo ***@***.***> a
écrit :

**Comment by zelurker** [comment]
And since it seems it still doesn't work, here is a link to this picture, I
give up !
https://raine.1emulation.com/archive/tux/raine2.png


Le dim. 1 janv. 2023 à 02:32, Emmanuel Anne ***@***.***> a
écrit :

**Comment by dezraj** [comment]
Thank you for the picture. Raine's old interface reminded me of the Zsnes emulator, which had a similar interface and which I used for some time.

Thank you again, and also for the technical details in the "About" screen, though I would think some translators would simply translate the text using Po Edit, and there it's difficult to check the string reference (in fact I don't even know if it's possible), and so we could have those inconsistencies in the translations in which some translators would respect this unusual space in the end of the string, and others don't. Anyway, I suppose you will have to keep an eye on that when a new translation comes eventually.

Thank you so much again.

**Comment by zelurker** [comment]
zsnes also used a lot of assembler, like raine, it was a very different
time !

Le lun. 2 janv. 2023 à 02:17, Elvis Araujo ***@***.***> a
écrit :

**Pull request closed without merging**
