### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by dezraj**
I have reviewed again some texts and messages in the menus. I think I have changed some messages which are only related to the debug, so maybe they are not really necessary to be changed and can perhaps break something in the code. Every commit has a summary of what was changed. Please check if everything is fine to be merged. Thank you so much in advance for your time and work.

### CODE REVIEW

**Comment by zelurker** [comment]
Yeah I am going to be tougher for this one, because changing all these
texts breaks the translations too, so :
when a text is passed to _("text") or gettext("text") it means this text is
translated. Which means that the text between the quotes is searched in one
of the .po files depending of the selected language. So for example, for
your 1st change, if you want to change "No speed limit !" by "No speed
limit!" (the space before the ! is what we do in France, but yeah in
english there is not supposed to be a space here by the way), then you must
also do the same change in locale/*.po :
es.po
french.po
it.po
pt_br.po
The format of the po files are just text files, the 1st line msgid gives
the string to be translated, that's the one you would want to change here,
and then just below you have the translation after msgstr, you should
probably not touch this, except if you want to make some changes in your
own language !

Sorry but I had no time nor motivation to fix the translations after your
previous changes, and it already broke the region switch (it's not the
change of text itself which broke it, it's the order of the options in the
menu, it's because there is a function which determines if an option should
be displayed or not and it works on the index of the entry in the menu, and
the region switch itself is a special case which needs some more
initialization, so if you move it around, the initializations are lost), so
I'd like to avoid to break them even more if you want to continue this...


Le dim. 25 déc. 2022 à 07:59, Elvis Araujo ***@***.***> a
écrit :

**Comment by zelurker** [comment]
And yeah, obviously printf is to print to the console for debugging
purposes so there is no need to touch this, and print_debug prints to the
debug file, same comment.

Le dim. 25 déc. 2022 à 14:43, Emmanuel Anne ***@***.***> a
écrit :

**Comment by zelurker** [comment]
Just finally updated the translations files for your previous changes. But at the same time I took the opportunity to finally update the reference .pot file with the source references + some eventual untranslated strings, and then updated the po files accordingly, so it's quite a big change. This should fix the translations to this point at least.

**Comment by zelurker** [comment]
And I just tried to apply manually your patches then regenerate the base .pot file and see if it can still find the right translations in the po files all by itself : it works for small changes, like the space before the !, but foreground instead of fg losses it, and you loose the translation. Which means it's still better to change directly the po files. At least now that they are updated with the correct string locations it's easier to check and update.
Sorry no magic here, manual work needed !

**Comment by dezraj** [comment]
Thank you so much for the technical details. I didn't expect it would give you such a work to implement these changes. Hopefully this will leave the texts more consistent in the code for future translations. ❤️

**Comment by zelurker** [comment]
Finally made a script to do your work, a perl script which decodes the git patch to find which translations change and updates the po files accordingly. I had to add your patch manually, editing it by hand to remove the not needed parts (printf, print_debug).
Anyway, took me 2 hours in the end, most of the time to make the script, in the end it works quite well.
Now there are quite a few fuzzy entries in the po files, but the meaning doesn't really change, it's just the choice of words so it's not too important.
So I am finally able to close this, what a pain... !

**Comment by dezraj** [comment]
Thank you so much for your work. I didn't expect it would take this much job to have these texts updated. Hopefully this script can be used in the future for quicker editions. I have commented in my Patch 2 PR too with some details on an issue I have spotted in the translation files.

Thank you again.

**Pull request closed without merging**
